namespace RadeonTuner
{
	[default_interface]
	runtimeclass DisplayDetailsIdl
	{
		DisplayDetailsIdl();
		Int32 IndexAdapter;
		Int32 IndexDisplay;
		String Name;
		Int32 ResolutionWidth;
		Int32 ResolutionHeight;
		Single RefreshRate;
	}
}